[versions]
dependencymanagement = "1.1.7"
flyway = "11.19.0"
flywaydb = "10.24.0"
h2db = "2.4.240"
jackson = "3.0.2"
jobrunr = "8.3.1"
junit = "6.0.1"
klogging = "7.0.13"
kotlin = "2.2.21"
kotlinx = "1.9.0"
manes = "0.53.0"
owasp = "12.1.9"
snakeyaml = "2.5"
springboot = "4.0.0"
sonarqube = "7.2.0.6526"
swagger = "3.0.0"
