[versions]
dependencymanagement = "1.1.7"
flyway = "11.19.1"
flywaydb = "10.24.0"
h2db = "2.4.240"
jackson = "2.20.1"
jobrunr = "8.2.4"
junit = "6.0.1"
klogging = "7.0.13"
kotlin = "2.3.0"
kotlinx = "1.9.0"
manes = "0.53.0"
owasp = "12.1.9"
snakeyaml = "2.5"
springboot = "3.5.9"
sonarqube = "7.2.2.6593"
swagger = "2.8.14"
