[versions]
dependencymanagement = "1.1.7"
flyway = "11.16.0"
flywaydb = "10.24.0"
h2db = "2.4.240"
jackson = "2.20.1"
jobrunr = "8.2.0"
junit = "6.0.1"
klogging = "7.0.13"
kotlin = "2.2.21"
kotlinx = "1.9.0"
manes = "0.53.0"
owasp = "12.1.8"
snakeyaml = "2.5"
springboot = "3.5.7"
sonarqube = "7.0.1.6134"
swagger = "2.8.14"
