[versions]
dependencymanagement = "1.1.7"
flyway = "12.0.0"
flywaydb = "10.24.0"
h2db = "2.4.240"
jackson = "3.0.3"
jobrunr = "8.4.2"
junit = "6.0.1"
klogging = "7.0.14"
kotlin = "2.3.10"
kotlinx = "1.10.0"
manes = "0.53.0"
owasp = "12.2.0"
snakeyaml = "2.5"
springboot = "4.0.2"
sonarqube = "7.2.2.6593"
swagger = "3.0.1"
